title: Services
template: service/show
revisions: false
route: '/service/{slug}'
date_behavior:
  past: public
  future: private
sites:
  - en
  - pl
  - sv
  - no
  - nl
  - lv
  - it
  - fr
  - es
  - de
  - da
  - cs
propagate: true
