title: Services
template: service/show
revisions: false
route:
  pl: '/oferta/{slug}'
  en: '/service/{slug}'
  sv: '/service/{slug}'
  'no': '/service/{slug}'
  nl: '/service/{slug}'
  lv: '/service/{slug}'
  it: '/service/{slug}'
  fr: '/service/{slug}'
  es: '/service/{slug}'
  de: '/service/{slug}'
  da: '/service/{slug}'
  cs: '/service/{slug}'
date_behavior:
  past: public
  future: private
sort_field: order
sort_direction: asc
sites:
  - en
  - pl
  - sv
  - no
  - nl
  - lv
  - it
  - fr
  - es
  - de
  - da
  - cs
propagate: true
